spring:
  main:
    allow-bean-definition-overriding: true
#  config:
#    activate:
#      on-profile: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: pass_local
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  port: 8082